# Hyprpaper configuration
# translated from nixos-config/home/hyprpaper.nix

ipc = false
splash = false

preload = $HOME/.config/wallpapers/climber.png
wallpaper = ,$HOME/.config/wallpapers/climber.png
